-- [프로그래머스]없어진 기록 찾기
-- ANIMAL_INS  보호소에 들어온 동물 정보
-- ANIMAL_OUTS 보호소에서 입양간 동물 정보
-- ANIMAL_ID 외래키
-- 데이터 유실 사건 : 입양을 갔는데 들어온 기록이 없음
-- ANIMAL_OUTS에 있지만 ANIMAL_INS에는 없음

SELECT OUTS.ANIMAL_ID, OUTS.NAME FROM ANIMAL_OUTS OUTS
LEFT OUTER JOIN ANIMAL_INS INS
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE INS.ANIMAL_ID IS NULL
ORDER BY OUTS.ANIMAL_ID